### ISSUE TITLE
Feature Request: When rendering templates (ex. with {~TS:Template:Datum~} it would be nice to have access to the parent record(s).

### ISSUE THREAD

**Issue by bigal-hl** [stevenvelozo/pict#6]
Ex. if you are rendering a nested template, and the parent record has some info that you need to check from the child. In my case, I want to put a class on the children so I can style them consistently, even though they may not know the parent info.

Option discussed:

Provide an array named `TemplateRecords` which behaves as a stack, where the "top" record is the same thing as `Record`, but `TemplateRecords[1]` has the parent template's record, and so on.

**Comment by stevenvelozo** [comment]
This has been implemented with a new Template Object:

When a template is rendered directly from pict, the template has `Context[0]` as the pict instance that rendered the template, `Context[1]` as the template's `Record` object, etc. down the chain of child templates.  The only subtle difference (that I'm considering changing a bit) is when you render from a view, right now `Context[0]` is the view rather than pict.

After using this for a bit, it seems like it might be neat to always have `Context[0]` be pict and `Context[1]` be the view if there is a view.  There are pros and cons of both.

Metatemplates use the UUID from the root context to construct truly distinct identifiers in HTML, and both the views and pict have a UUID property so this just kindof magically works.
